# Workflow for deploying your Vite app to GitHub Pages
name: Deploy Vite App to Pages

on:
  # Runs on pushes targeting the 'main' branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use a recent Long-Term Support version of Node.js
          # The cache was corrupted. Disabling it to force a fresh install.
          # cache: 'npm' 
      - name: Install dependencies
        run: npm ci
      - name: Build project
        # This command runs "vite build" as defined in your package.json
        # Vite will use the 'base: "/Aegis/"' setting from your vite.config.ts
        run: npm run build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'dist' folder that 'npm run build' creates
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
